// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.google.guava" % "guava" % "19.0",
  "net.jpountz.lz4" % "lz4" % "1.3.0",
  "org.slf4j" % "slf4j-api" % "1.7.25"
)
// LIBRARY_DEPENDENCIES_HASH 2e09119f214899a590858513e31ba678ebd6d448
