// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.2.3.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.google.guava" % "guava" % "18.0",
  "com.novocode" % "junit-interface" % "0.11",
  "junit" % "junit" % "4.11",
  "org.hamcrest" % "hamcrest-core" % "1.3",
  "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.2",
  "org.scala-sbt" % "test-interface" % "1.0",
  "org.scalacheck" % "scalacheck_2.11" % "1.12.5",
  "org.scalactic" % "scalactic_2.11" % "2.3.0-SNAP2",
  "org.scalatest" % "scalatest_2.11" % "2.3.0-SNAP2",
  "org.slf4j" % "slf4j-api" % "1.7.21"
)
// LIBRARY_DEPENDENCIES_HASH 5c61accdaeb77d376d28421c103e1d50df7875db
